karpenter:
  serviceAccount:
    create: false
  serviceMonitor:
    enabled: true
  replicas: 2
  revisionHistoryLimit: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 1
  podDisruptionBudget:
    name: karpenter-pbd
    maxUnavailable: 1
  priorityClassName: system-cluster-critical
  nodeSelector:
    kubernetes.io/os: linux
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: karpenter.sh/provisioner-name
                operator: DoesNotExist
  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: topology.kubernetes.io/zone
      whenUnsatisfiable: ScheduleAnyway
  tolerations:
    - key: CriticalAddonsOnly
      operator: Exists
  controller:
    resources:
      requests:
        cpu: 500m
        memory: 200Mi
      limits:
        cpu: 1
        memory: 500Mi
  logLevel: debug
  settings:
    aws:
      clusterName:
      clusterEndpoint:
      defaultInstanceProfile: eks-d4c618af-8e49-8b34-bf05-cb5e842b756c
      interruptionQueueName:
