{{- if and (.Values.karpenter) (.Values.karpenter.enable) -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter
  namespace: {{ .Values.argoNamespace | default "argocd" }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.argoProject | default "default" }}
  sources:
    - repoURL: {{ .Values.repoUrl }}
      path: add-ons/karpenter
      targetRevision: {{ .Values.targetRevision }}
      helm:
        parameters:
          - name: karpenter.serviceAccount.name
            value: {{ .Values.karpenter.serviceAccountName }}
          - name: karpenter.settings.aws.clusterName
            value: {{ .Values.clusterName }}
          - name: karpenter.settings.aws.clusterEndpoint
            value: {{ .Values.karpenter.controllerClusterEndpoint }}
          - name: karpenter.settings.aws.defaultInstanceProfile
            value: {{ .Values.karpenter.awsDefaultInstanceProfile }}
          - name: karpenter.settings.aws.interruptionQueueName
            value: {{ .Values.karpenter.awsInterruptionQueueName }}
    - repoURL: git@gitlab.com:openinnovationai/platform/infra/argocd-deploy.git
      path: aws-prod/apps/eks-blueprints/karpenter
      targetRevision: HEAD
  destination:
    server: {{ .Values.destinationServer | default "https://kubernetes.default.svc" }}
    namespace: karpenter
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace={{ .Values.karpenter.createNamespace }}
    retry:
      limit: 1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
  ignoreDifferences:
    - kind: Secret
      name: karpenter-cert
      namespace: karpenter
      jsonPointers:
        - /data
{{- end -}}