{{- if and (.Values.karpenter) (.Values.karpenter.enable) -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter
  namespace: {{ .Values.argoNamespace | default "argocd" }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.argoProject | default "default" }}
  sources:
    - repoURL: {{ .Values.repoUrl }}
      path: add-ons/karpenter
      targetRevision: {{ .Values.targetRevision }}
      helm:
        values: |
          karpenter:
            serviceAccount:
              create: false
            serviceMonitor:
              enabled: true
            replicas: 2
            revisionHistoryLimit: 1
            strategy:
              rollingUpdate:
                maxUnavailable: 1
            podDisruptionBudget:
              name: karpenter-pbd
              maxUnavailable: 1
            priorityClassName: system-cluster-critical
            nodeSelector:
              kubernetes.io/os: linux
            affinity:
              nodeAffinity:
                requiredDuringSchedulingIgnoredDuringExecution:
                  nodeSelectorTerms:
                    - matchExpressions:
                        - key: karpenter.sh/provisioner-name
                          operator: DoesNotExist
            topologySpreadConstraints:
              - maxSkew: 1
                topologyKey: topology.kubernetes.io/zone
                whenUnsatisfiable: ScheduleAnyway
            tolerations:
              - key: CriticalAddonsOnly
                operator: Exists
            controller:
              resources:
                requests:
                  cpu: 500m
                  memory: 200Mi
                limits:
                  cpu: 1
                  memory: 500Mi
            logLevel: debug
            settings:
              aws:
                clusterName: ""
                clusterEndpoint: ""
                defaultInstanceProfile: eks-d4c618af-8e49-8b34-bf05-cb5e842b756c
                interruptionQueueName: ""
        parameters:
          - name: karpenter.serviceAccount.name
            value: {{ .Values.karpenter.serviceAccountName }}
          - name: karpenter.settings.aws.clusterName
            value: {{ .Values.clusterName }}
          - name: karpenter.settings.aws.clusterEndpoint
            value: {{ .Values.karpenter.controllerClusterEndpoint }}
          - name: karpenter.settings.aws.defaultInstanceProfile
            value: {{ .Values.karpenter.awsDefaultInstanceProfile }}
          - name: karpenter.settings.aws.interruptionQueueName
            value: {{ .Values.karpenter.awsInterruptionQueueName }}
    - repoURL: git@gitlab.com:openinnovationai/platform/infra/argocd-deploy.git
      path: aws-prod/apps/eks-blueprints/karpenter
      targetRevision: HEAD
  destination:
    server: {{ .Values.destinationServer | default "https://kubernetes.default.svc" }}
    namespace: karpenter
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace={{ .Values.karpenter.createNamespace }}
    retry:
      limit: 1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
  ignoreDifferences:
    - kind: Secret
      name: karpenter-cert
      namespace: karpenter
      jsonPointers:
        - /data
  {{- end -}}