cert-manager:
  logLevel: 2
  installCRDs: true
  replicaCount: 2
  controller:
    replicaCount: 2
    image:
      debug: false
    acmesolver:
      image:
        debug: false
    resources:
      requests:
        cpu: 50m
        memory: 35Mi
      limits:
        cpu: 200m
        memory: 60Mi
  webhook:
    replicaCount: 2
    image:
      debug: false
    resources:
      requests:
        cpu: 50m
        memory: 20Mi
      limits:
        cpu: 200m
        memory: 50Mi
  cainjector:
    replicaCount: 2
    image:
      debug: false
    resources:
      requests:
        cpu: 50m
        memory: 80Mi
      limits:
        cpu: 200m
        memory: 124Mi
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: "kube-prometheus-stack"